# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Jiarong Qiu's Workspace
tagline:             ''
description:         'This my personal space to document EVERYTHING!'
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:             2
paginate_path:        /page:num/

# About/contact
author:
  name:              Jiarong Qiu
  url:               https://twitter.com/mdo
  email:             jiarong_qiu@sina.com

# Custom vars
version:             1.0.0
excerpt_separator: <!--excerpt-->